library(readxl)
CropYield <- as.data.frame(read_excel("adatok_abrakhoz_Peternek.xlsx"))
as.numeric(as.matrix((CropYield[2:12,])))

CropYield.clLo <- as.data.frame(read_excel("adatok_abrakhoz_Peternek.xlsx",range="A2:K13"))

par(mfrow = c(2,3), las = 2, mar = c(3.1,0,0,0), oma = c(0,2.1,1.1,0.1))
barplot(t(as.matrix(CropYield.clLo[,2:4])), beside = TRUE, col = NA, border = NA, ylim = c(0,13))
grid(nx=NA, ny = NULL)
barplot(t(as.matrix(CropYield.clLo[,2:4])), beside = TRUE, col = GWcolors, ylim = c(0,13), names.arg = 2000:2010, add = TRUE)
box()
barplot(t(as.matrix(CropYield.clLo[,5:7])), beside = TRUE, col = NA, border = NA, ylim = c(0,13), axes = FALSE)
grid(nx=NA, ny = NULL)
barplot(t(as.matrix(CropYield.clLo[,5:7])), beside = TRUE, col = GWcolors, ylim = c(0,13), names.arg = 2000:2010, axes = FALSE, add = TRUE)
box()
barplot(t(as.matrix(CropYield.clLo[,8:10])), beside = TRUE, col = NA, border = NA, ylim = c(0,13), axes = FALSE)
grid(nx=NA, ny = NULL)
barplot(t(as.matrix(CropYield.clLo[,8:10])), beside = TRUE, col = GWcolors, ylim = c(0,13), names.arg = 2000:2010, axes = FALSE, add = TRUE)
box()
