library(readxl)
CropYield <- as.data.frame(read_excel("adatok_abrakhoz_Peternek.xlsx"))
as.numeric(as.matrix((CropYield[2:12,])))

CropYield.clLo <- as.data.frame(read_excel("adatok_abrakhoz_Peternek.xlsx",range="A2:K13"))
CropYield.siCl <- as.data.frame(read_excel("adatok_abrakhoz_Peternek.xlsx",range="A16:K27"))
CropYield.loSa <- as.data.frame(read_excel("adatok_abrakhoz_Peternek.xlsx",range="A30:K41"))

par(mfrow = c(3,3), las = 2, mar = c(2.4,0,0,0), oma = c(2.5,2.6,3.1,0.1))
barplot(t(as.matrix(CropYield.clLo[,2:4])), beside = TRUE, col = NA, border = NA, ylim = c(0,13))
mtext("shallow GW", las = 1, line = 1)
mtext("clLo", at = -2.5, las = 1, font = 2)
grid(nx=NA, ny = NULL)
barplot(t(as.matrix(CropYield.clLo[,2:4])), beside = TRUE, col = GWcolors, ylim = c(0,13), names.arg = 2000:2010, axes = FALSE, add = TRUE, mgp = c(3,0.2,0))
box()
barplot(t(as.matrix(CropYield.clLo[,5:7])), beside = TRUE, col = NA, border = NA, ylim = c(0,13), axes = FALSE)
mtext("medium GW", las = 1, line = 1)
grid(nx=NA, ny = NULL)
barplot(t(as.matrix(CropYield.clLo[,5:7])), beside = TRUE, col = GWcolors, ylim = c(0,13), names.arg = 2000:2010, axes = FALSE, add = TRUE, mgp = c(3,0.2,0))
box()
barplot(t(as.matrix(CropYield.clLo[,8:10])), beside = TRUE, col = NA, border = NA, ylim = c(0,13), axes = FALSE)
mtext("deep GW", las = 1, line = 1)
grid(nx=NA, ny = NULL)
barplot(t(as.matrix(CropYield.clLo[,8:10])), beside = TRUE, col = GWcolors, ylim = c(0,13), names.arg = 2000:2010, axes = FALSE, add = TRUE, mgp = c(3,0.2,0))
box()
## 2nd row
barplot(t(as.matrix(CropYield.siCl[,2:4])), beside = TRUE, col = NA, border = NA, ylim = c(0,13))
mtext("siCl", at = -2.5, las = 1, font = 2)
grid(nx=NA, ny = NULL)
barplot(t(as.matrix(CropYield.siCl[,2:4])), beside = TRUE, col = GWcolors, ylim = c(0,13), names.arg = 2000:2010, axes = FALSE, add = TRUE, mgp = c(3,0.2,0))
box()
barplot(t(as.matrix(CropYield.siCl[,5:7])), beside = TRUE, col = NA, border = NA, ylim = c(0,13), axes = FALSE)
grid(nx=NA, ny = NULL)
barplot(t(as.matrix(CropYield.siCl[,5:7])), beside = TRUE, col = GWcolors, ylim = c(0,13), names.arg = 2000:2010, axes = FALSE, add = TRUE, mgp = c(3,0.2,0))
box()
barplot(t(as.matrix(CropYield.siCl[,8:10])), beside = TRUE, col = NA, border = NA, ylim = c(0,13), axes = FALSE)
grid(nx=NA, ny = NULL)
barplot(t(as.matrix(CropYield.siCl[,8:10])), beside = TRUE, col = GWcolors, ylim = c(0,13), names.arg = 2000:2010, axes = FALSE, add = TRUE, mgp = c(3,0.2,0))
box()
## 3rd row
barplot(t(as.matrix(CropYield.loSa[,2:4])), beside = TRUE, col = NA, border = NA, ylim = c(0,13))
mtext("loSa", at = -2.5, las = 1, font = 2)
grid(nx=NA, ny = NULL)
barplot(t(as.matrix(CropYield.loSa[,2:4])), beside = TRUE, col = GWcolors, ylim = c(0,13), names.arg = 2000:2010, axes = FALSE, add = TRUE, mgp = c(3,0.2,0))
box()
barplot(t(as.matrix(CropYield.loSa[,5:7])), beside = TRUE, col = NA, border = NA, ylim = c(0,13), axes = FALSE)
grid(nx=NA, ny = NULL)
barplot(t(as.matrix(CropYield.loSa[,5:7])), beside = TRUE, col = GWcolors, ylim = c(0,13), names.arg = 2000:2010, axes = FALSE, add = TRUE, mgp = c(3,0.2,0))
legend("bottom", inset = c(0, -0.22),
       legend = c("Reference", "Passive", "Active", "Rainfed conditions"),
       col = c(GWcolors, 1) , lwd = 4, ncol = 4, xpd = NA)
box()
barplot(t(as.matrix(CropYield.loSa[,8:10])), beside = TRUE, col = NA, border = NA, ylim = c(0,13), axes = FALSE)
grid(nx=NA, ny = NULL)
barplot(t(as.matrix(CropYield.loSa[,8:11])), beside = TRUE, col = c(GWcolors, 1), ylim = c(0,13), names.arg = 2000:2010, axes = FALSE, add = TRUE, mgp = c(3,0.2,0))
box()
